# --- Ansible behavior ---
ansible_become: true  # Most package installations require sudo

# --- User and Paths ---
ssh_public_key_path: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
local_workspace_dir: >-
  {{ ansible_env.HOME }}/local_zuul_ansible_setup_ws

# --- Gerrit Configuration ---
local_gerrit_admin_user: "admin"
gerrit_ssh_port: 29418
gerrit_http_port: 8080
gerrit_url: "http://localhost:{{ gerrit_http_port }}"
gerrit_ssh_url_base: >-
  ssh://{{ local_gerrit_admin_user }}@localhost:{{ gerrit_ssh_port }}

# --- Zuul Podman Setup ---
zuul_quickstart_repo_url: "https://opendev.org/zuul/zuul"
zuul_quickstart_repo_dest: >-
  {{ local_workspace_dir }}/zuul_quickstart_src
zuul_podman_compose_project_name: "zuulzilla_ci"

# --- Projects to configure in Gerrit/Zuul ---
zuul_config_project_name: "zuul-config"
zuul_config_local_repo_path: >-
  {{ local_workspace_dir }}/gerrit_repos/{{ zuul_config_project_name }}

ironic_tempest_plugin_project_name: "ironic-tempest-plugin"
local_ironic_tempest_plugin_path: >-
  {{ ansible_env.HOME }}/path/to/your/ironic-tempest-plugin  # CHANGE THIS
managed_ironic_tempest_plugin_repo_path: >-
  {{ local_workspace_dir }}/gerrit_repos/{{ ironic_tempest_plugin_project_name }}

# --- DevStack settings for Zuul job playbooks ---
devstack_admin_password: "supersecretpassword"
devstack_default_branch: "master"
#tempest_test_regex: 'ironic_tempest_plugin.tests.scenario'
tempest_test_regex: 'ironic_tempest_plugin.tests.api' # Functional Test (API)

# --- Common Prerequisites ---
common_packages:
  - git
  - python3-pip
  - podman
