---
- hosts: localhost
  gather_facts: true

  vars:
    # Ensure this path is correct for your system if not using default
    ssh_public_key_content: >-
      {{ lookup('file', ssh_public_key_path) }}

  pre_tasks:
    - name: Welcome message and prerequisite check
      ansible.builtin.pause:
        prompt: |
          This playbook will automate the setup of a local Zuul & Gerrit
          environment. It assumes:
          1. You have Ansible, Podman, Git, and Python pip.
          2. You have an SSH key at {{ ssh_public_key_path }}.
          3. You will manually create your Gerrit user
             '{{ local_gerrit_admin_user }}', add this SSH key, and grant it
             Administrator rights in the Gerrit UI when prompted.
          4. You will manually approve the first 'zuul-config' change in
             Gerrit when prompted.
          Press Enter to continue or Ctrl+C to abort.

    - name: Create local workspace directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ local_workspace_dir }}"
        - "{{ local_workspace_dir }}/gerrit_repos"

  roles:
    - role: common_prereqs
    - role: zuul_gerrit_containers
      vars:
        action: "up"
    - role: gerrit_zuul_config
