---
- hosts: localhost
  gather_facts: false

  roles:
    - role: zuul_gerrit_containers
      vars:
        action: "down"

  post_tasks:
    - name: Inform about manual cleanup if needed
      ansible.builtin.debug:
        msg: |
          Containers have been stopped and removed.
          The workspace at {{ local_workspace_dir }} still exists.
          You may want to remove it manually: rm -rf {{ local_workspace_dir }}
          Podman volumes might also persist if not explicitly removed by
          podman-compose.
