---
# Args:
#   repo_local_path: local path to the git repo
#   gerrit_project_name: name of the project in Gerrit
#   commit_message: commit message for initial commit
#   push_to_review: boolean, if true push to refs/for/master,
#                   else push to refs/heads/master

- name: Set git user info for {{ gerrit_project_name }} commit
  ansible.builtin.command: >
    git config user.name 'Ansible Automation' &&
    git config user.email 'ansible@localhost'
  args:
    chdir: "{{ repo_local_path }}"
  changed_when: false

- name: Add git remote 'localgerrit' for {{ gerrit_project_name }}
  ansible.builtin.command: >
    git remote add localgerrit
    {{ gerrit_ssh_url_base }}/{{ gerrit_project_name }}
  args:
    chdir: "{{ repo_local_path }}"
  register: add_remote_result
  failed_when: >
    add_remote_result.rc != 0 and
    'remote localgerrit already exists'
    not in add_remote_result.stderr
  changed_when: add_remote_result.rc == 0

- name: Add all changes in {{ repo_local_path }}
  ansible.builtin.command: git add .
  args:
    chdir: "{{ repo_local_path }}"
  changed_when: true

- name: Commit changes for {{ gerrit_project_name }}
  ansible.builtin.command: >
    git commit -m '{{ commit_message }}'
  args:
    chdir: "{{ repo_local_path }}"
  register: commit_result
  failed_when: >
    commit_result.rc != 0 and
    'nothing to commit' not in commit_result.stdout and
    'No changes' not in commit_result.stdout
  changed_when: >
    'nothing to commit' not in commit_result.stdout and
    'No changes' not in commit_result.stdout

- name: Push {{ gerrit_project_name }} to local Gerrit
  ansible.builtin.command: >
    git push localgerrit HEAD:refs/{{
      'for' if push_to_review else 'heads'
    }}/master {{ '-f' if not push_to_review else '' }}
  args:
    chdir: "{{ repo_local_path }}"
  changed_when: true

