---
# Args:
#   project_managed_path: path to the repo Ansible will manage for Gerrit push
#   project_gerrit_name: name of the project in Gerrit

- name: Ensure managed project directory exists for {{ project_gerrit_name }}
  ansible.builtin.file:
    path: "{{ project_managed_path }}"
    state: directory
    mode: '0755'

- name: Initialize git if .git is missing in {{ project_managed_path }}
  ansible.builtin.command: "git init"
  args:
    chdir: "{{ project_managed_path }}"
    creates: "{{ project_managed_path }}/.git"
  changed_when: true

- name: Add placeholder file if repo {{ project_gerrit_name }} is empty
  ansible.builtin.copy:
    src: "placeholder.txt"
    dest: "{{ project_managed_path }}/placeholder.txt"
  when: >
    (ansible.builtin.find(
      paths=project_managed_path,
      hidden=true,
      patterns='',
      recurse=false,
      file_type='any') | length) == 0

- name: Template .gitreview for {{ project_gerrit_name }}
  ansible.builtin.template:
    src: "gitreview.template.j2"
    dest: "{{ project_managed_path }}/.gitreview"
  vars:
    project_name_for_gitreview: "{{ project_gerrit_name }}"
  notify: "Commit and Push {{ project_gerrit_name }}"
