---
- name: Clone Zuul repository for podman-compose files
  ansible.builtin.git:
    repo: "{{ zuul_quickstart_repo_url }}"
    dest: "{{ zuul_quickstart_repo_dest }}"
    version: master  # Or a specific stable tag
  when: action == "up"

- name: Start Zuul, Gerrit, Nodepool containers
  ansible.builtin.command:
    cmd: >
      podman-compose -p {{ zuul_podman_compose_project_name }} up -d
    chdir: >
      {{ zuul_quickstart_repo_dest }}/doc/source/examples
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
  register: podman_compose_up_result
  changed_when: >
    'Creating' in podman_compose_up_result.stdout or
    'Starting' in podman_compose_up_result.stdout
  failed_when: >
    podman_compose_up_result.rc != 0 and
    not (
      'is already running' in podman_compose_up_result.stderr or
      (
        'Error:  container name' in podman_compose_up_result.stderr and
        'is already in use' in podman_compose_up_result.stderr
      )
    )
  when: action == "up"

- name: Stop and remove Zuul, Gerrit, Nodepool containers
  ansible.builtin.command:
    cmd: >
      podman-compose -p {{ zuul_podman_compose_project_name }} down
    chdir: >
      {{ zuul_quickstart_repo_dest }}/doc/source/examples
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
  when: action == "down"
  ignore_errors: true
