---
- name: Install common prerequisite packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present
  register: pkg_install_result
  failed_when: >
    pkg_install_result.rc != 0 and
    'No package matching' not in pkg_install_result.msg and
    'Nothing to do' not in pkg_install_result.msg

- name: Ensure pip is available (alternative for some systems)
  ansible.builtin.command: python3 -m ensurepip --upgrade
  when: >
    pkg_install_result.failed or
    "'python3-pip' not found" in pkg_install_result.msg
  changed_when: false
  ignore_errors: true

- name: Install podman-compose using pip
  ansible.builtin.pip:
    name:
      - podman-compose
      - git-review
    state: present
    executable: python3 -m pip
  # become: true

- name: Verify SSH public key exists
  ansible.builtin.stat:
    path: "{{ ssh_public_key_path }}"
  register: ssh_key_stat
  failed_when: not ssh_key_stat.stat.exists
  vars:
    ansible_warning_implicit_localhost: false

- name: Display SSH public key to be used for Gerrit
  ansible.builtin.debug:
    msg: >
      Ensure the following SSH public key is added to your
      '{{ local_gerrit_admin_user }}' Gerrit account:
      {{ lookup('file', ssh_public_key_path) }}

